name = "new-life-live-status"
main = "cloudflare-worker-live-status.js"
compatibility_date = "2024-03-01"

# KV namespace for caching live status
[[kv_namespaces]]
binding = "LIVE_STATUS_CACHE"
id = "e03c580a8f524dcd82ec942f89e8db8f" 